# Generated by Django 6.0.1 on 2026-01-26 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('pontos_minimos', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='crianca',
            name='idade',
        ),
        migrations.CreateModel(
            name='PartidaJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.crianca')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEducacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escova_noite', models.BooleanField(default=False)),
                ('usa_fio_dental', models.BooleanField(default=False)),
                ('conhecimento_geral', models.IntegerField(default=0)),
                ('crianca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.crianca')),
            ],
        ),
        migrations.CreateModel(
            name='CriancaBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.badge')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.crianca')),
            ],
            options={
                'unique_together': {('crianca', 'badge')},
            },
        ),
    ]
