# Generated by Django 6.0.1 on 2026-02-15 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_badge_remove_crianca_idade_partidajogo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='criancabadge',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='criancabadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to='game.badge'),
        ),
        migrations.AlterField(
            model_name='criancabadge',
            name='crianca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges_conquistados', to='game.crianca'),
        ),
        migrations.AlterField(
            model_name='partidajogo',
            name='crianca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='game.crianca'),
        ),
    ]
