# Generated by Django 6.0.1 on 2026-02-18 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_criancabadge_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('quantidade_necessaria', models.IntegerField()),
                ('badge_requerida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.badge')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressoPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_atual', models.IntegerField(default=0)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.crianca')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.premio')),
            ],
        ),
    ]
