# Generated by Django 6.0.1 on 2026-02-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_premio_progressopremio'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidajogo',
            name='dificuldade',
            field=models.CharField(default='facil', max_length=20),
        ),
    ]
