# Generated by Django 6.0.1 on 2026-02-23 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_partidajogo_dificuldade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('asset_nome', models.CharField(max_length=100)),
                ('pontos_necessarios', models.IntegerField()),
                ('ordem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CriancaPersonagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False)),
                ('data_desbloqueio', models.DateTimeField(auto_now_add=True)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagens', to='game.crianca')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.personagem')),
            ],
            options={
                'unique_together': {('crianca', 'personagem')},
            },
        ),
    ]
