# Generated by Django 6.0.1 on 2026-02-23 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_personagem_criancapersonagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personagem',
            name='ordem',
        ),
        migrations.AlterField(
            model_name='criancapersonagem',
            name='crianca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagens_desbloqueados', to='game.crianca'),
        ),
    ]
