# Generated by Django 6.0.1 on 2026-01-22 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.crianca')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.pergunta')),
            ],
        ),
    ]
