# Generated by Django 6.0.2 on 2026-02-23 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0005_partidajogo_dificuldade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('pontos', models.IntegerField(default=0)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='questions.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='TentativaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('score_total', models.IntegerField(default=0)),
                ('resultado', models.CharField(default='', max_length=30)),
                ('finalizado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_questionario', to='game.crianca')),
            ],
            options={
                'unique_together': {('crianca', 'ano', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('alternativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.alternativa')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.pergunta')),
                ('tentativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questions.tentativamensal')),
            ],
            options={
                'unique_together': {('tentativa', 'pergunta')},
            },
        ),
    ]
