# Generated by Django 6.0.2 on 2026-02-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_personagem_ordem_and_more'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TentativaMensal',
            new_name='Tentativa',
        ),
    ]
