# Generated by Django 6.0.2 on 2026-03-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_rename_tentativamensal_tentativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentativa',
            name='resultado',
            field=models.CharField(default='', max_length=120),
        ),
    ]
